### ISSUE TITLE
Pass the query execution to mongodb level

### ISSUE THREAD

**Issue by PrabodDunuwila** [siddhi-io/siddhi-store-mongodb#55]
**Description:**
Improve the siddhi MongoDB connector to execute the select queries at the database level such as having, group by, order by

**Comment by niveathika** [comment]
Pull request opened in https://github.com/siddhi-io/siddhi-store-mongodb/pull/56

**Comment by niveathika** [comment]
Closing as the bove improvement is added in the #56
